hamming:		hamming-encode hamming-decode

hamming-encode:		main.o hamming.o
			gcc main.o hamming.o -o hamming-encode 

hamming-encode:		main.o hamming.o
			gcc main.o hamming.o -o hamming-decode

clean:
			rm -f *~ *.o hello
